set timeout 600
spawn ssh -o StrictHostKeyChecking=no abdulmuhaimin@34.142.226.77
expect {
    "Enter passphrase for key*" {
        send "Memin@9994061\r"
        exp_continue
    }
    "$ " {
        send "cd /var/www/html && sudo env GIT_SSH_COMMAND='ssh -i /home/abdulmuhaimin/.ssh/id_ed25519 -o StrictHostKeyChecking=no' git fetch origin uat && sudo git reset --hard origin/uat && sudo php artisan migrate --force && sudo npm install && sudo npm run build && sudo php artisan optimize && echo 'DEPLOYMENT_COMPLETE_SUCCESS' && exit\r"
    }
}
expect eof
