<?php

namespace App\Support;

use App\Models\User;

class PlayerContact
{
    /**
     * Login addresses generated by registration and the masterbase import.
     * They are account keys, not inboxes the player controls.
     */
    public static function isPlaceholderEmail(?string $email): bool
    {
        if ($email === null || trim($email) === '') {
            return true;
        }

        return str_ends_with(strtolower(trim($email)), '@vellarleague.com');
    }

    public static function usableEmail(?string $email): ?string
    {
        $email = strtolower(trim((string) $email));

        if ($email === '' || ! filter_var($email, FILTER_VALIDATE_EMAIL)) {
            return null;
        }

        if (self::isPlaceholderEmail($email)) {
            return null;
        }

        return $email;
    }

    public static function usablePhone(?string $phone): ?string
    {
        $digits = preg_replace('/\D/', '', (string) $phone) ?? '';

        if (strlen($digits) < 8 || strlen($digits) > 15) {
            return null;
        }

        return $digits;
    }

    public static function canReceiveEmail(User $user): bool
    {
        return self::usableEmail($user->contact_email) !== null;
    }

    public static function canReceiveSms(User $user): bool
    {
        return self::usablePhone($user->phone) !== null;
    }
}
