name: Deploy NUVRA to Local Office Server (UAT)

on:
  push:
    branches: [ uat ]

jobs:
  deploy:
    runs-on: [self-hosted, uat]

    steps:
      - name: Deploy UAT Codebase
        run: |
          cd /home/muhaimin/nuvra-uat
          git config --global --add safe.directory /home/muhaimin/nuvra-uat
          
          # Sync with GitHub (Force)
          git fetch origin uat
          git reset --hard origin/uat
          
          # Backend dependencies
          composer install --no-interaction --optimize-autoloader
          
          # Frontend build
          npm install
          npm run build
          
          # Database & Optimization
          php artisan migrate --force
          php artisan optimize:clear
          php artisan optimize
          php artisan view:cache
          
          # Permissions for web server (nginx / php-fpm)
          chmod 666 nuvra_db || true
          chmod -R 777 storage bootstrap/cache || true

